import { Platform } from "react-native";

export const Colors = {
  light: {
    text: "#111827",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    textOnPrimary: "#FFFFFF",
    textOnAccent: "#FFFFFF",
    buttonText: "#FFFFFF",
    tabIconDefault: "#9CA3AF",
    tabIconSelected: "#FF6B2C",
    link: "#2563EB",
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#F9FAFB",
    backgroundSecondary: "#F3F4F6",
    backgroundTertiary: "#E5E7EB",
    primary: "#1F3650",
    primaryLight: "#2D4A6A",
    primaryDark: "#152538",
    accent: "#FF6B2C",
    accentLight: "#FF8F5C",
    accentDark: "#E55A1F",
    statusIdle: "#9CA3AF",
    statusOpen: "#3B82F6",
    statusInProgress: "#F59E0B",
    statusCompleted: "#10B981",
    statusCancelled: "#EF4444",
    fillLow: "#10B981",
    fillMedium: "#F59E0B",
    fillHigh: "#EF4444",
    fillCritical: "#991B1B",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    error: "#EF4444",
    errorLight: "#FEE2E2",
    warning: "#F59E0B",
    warningLight: "#FEF3C7",
    success: "#10B981",
    successLight: "#D1FAE5",
    info: "#3B82F6",
    infoLight: "#DBEAFE",
    cardSurface: "#FFFFFF",
    cardBorder: "#E5E7EB",
    cardSurfaceElevated: "#FFFFFF",
    overlay: "rgba(0, 0, 0, 0.5)",
    divider: "#E5E7EB",
  },
  dark: {
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    textOnPrimary: "#FFFFFF",
    textOnAccent: "#FFFFFF",
    buttonText: "#FFFFFF",
    tabIconDefault: "#6B7280",
    tabIconSelected: "#FF6B2C",
    link: "#60A5FA",
    backgroundRoot: "#111827",
    backgroundDefault: "#1F2937",
    backgroundSecondary: "#374151",
    backgroundTertiary: "#4B5563",
    primary: "#3B82F6",
    primaryLight: "#60A5FA",
    primaryDark: "#1D4ED8",
    accent: "#FF6B2C",
    accentLight: "#FF8F5C",
    accentDark: "#E55A1F",
    statusIdle: "#6B7280",
    statusOpen: "#60A5FA",
    statusInProgress: "#FBBF24",
    statusCompleted: "#34D399",
    statusCancelled: "#F87171",
    fillLow: "#34D399",
    fillMedium: "#FBBF24",
    fillHigh: "#F87171",
    fillCritical: "#DC2626",
    border: "#374151",
    borderLight: "#4B5563",
    error: "#F87171",
    errorLight: "#7F1D1D",
    warning: "#FBBF24",
    warningLight: "#78350F",
    success: "#34D399",
    successLight: "#064E3B",
    info: "#60A5FA",
    infoLight: "#1E3A8A",
    cardSurface: "#1F2937",
    cardBorder: "#374151",
    cardSurfaceElevated: "#374151",
    overlay: "rgba(0, 0, 0, 0.75)",
    divider: "#374151",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 56,
  buttonHeight: 56,
  buttonHeightSmall: 48,
  tabBarHeight: 64,
  touchTargetMin: 48,
};

export const BorderRadius = {
  xs: 6,
  sm: 10,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  full: 9999,
};

export const Typography = {
  h1: {
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 38,
  },
  h2: {
    fontSize: 28,
    fontWeight: "700" as const,
    lineHeight: 34,
  },
  h3: {
    fontSize: 24,
    fontWeight: "600" as const,
    lineHeight: 31,
  },
  h4: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 26,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 24,
  },
  bodyBold: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 24,
  },
  small: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
  },
  smallBold: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 20,
  },
  caption: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 17,
  },
  captionBold: {
    fontSize: 12,
    fontWeight: "700" as const,
    lineHeight: 17,
  },
  button: {
    fontSize: 16,
    fontWeight: "700" as const,
    letterSpacing: 0.3,
  },
  buttonSmall: {
    fontSize: 14,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
  label: {
    fontSize: 13,
    fontWeight: "600" as const,
    letterSpacing: 0.4,
  },
  link: {
    fontSize: 16,
    fontWeight: "500" as const,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, sans-serif",
    mono: "'SF Mono', SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
  },
});

export const Shadows = {
  none: {
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  small: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  medium: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  large: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  xl: {
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.10,
    shadowRadius: 16,
    elevation: 8,
  },
};

export const IndustrialDesign = {
  minTouchTarget: 48,
  buttonHeight: 56,
  buttonHeightSmall: 48,
  borderWidth: 2,
  borderWidthThin: 1,
  iconSize: 24,
  iconSizeLarge: 28,
  iconSizeXL: 32,
  cardPadding: 16,
  cardPaddingLarge: 20,
  listItemHeight: 72,
  listItemHeightCompact: 56,
  statusBadgeHeight: 28,
  statusBadgePaddingH: 12,
  filterChipHeight: 44,
  headerHeight: 56,
};

export const AnimationConfig = {
  duration: {
    fast: 150,
    normal: 250,
    slow: 400,
  },
  spring: {
    damping: 20,
    stiffness: 300,
    mass: 0.8,
  },
  pressScale: 0.97,
  pressOpacity: 0.85,
};
